import{a as f,S as L,i as n}from"./assets/vendor-0Fq3u7cb.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&d(u)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();f.defaults.baseURL="https://pixabay.com/";async function m(a,t){const s={key:"44685360-74500565ee10f6b109a60bbe8",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await f.get("api/",{params:s})).data}const b=new L(".gallery-list a",{captionsData:"alt",captionsDelay:250}),S=document.querySelector(".gallery-list");function h(a){const t=a.map(s=>`<li class="gallery-item">
      <a href='${s.largeImageURL}' class="gallery-link">
      <img src='${s.webformatURL}' 
      alt='${s.tags}'
    width=360
      height=200
      class="gallery-image"/>
    </a>
      <div class="info-image"> 
        <p class="info-text"> LIKES: <span class="info-image-span">${s.likes} </span></p>
        <p class="info-text"> VIEWS:<span class="info-image-span">${s.views} </span></p>
         <p class="info-text"> COMMENTS:<span class="info-image-span">${s.comments} </span></p>
        <p class="info-text"> DOWNLOADS:<span class="info-image-span">${s.downloads} </span></p>
      </div>
    </li>`).join("");S.insertAdjacentHTML("beforeend",t),b.refresh()}const r={input:document.querySelector(".form-input"),btn:document.querySelector(".search-btn"),searchForm:document.querySelector(".search-form"),picturesList:document.querySelector(".gallery-list"),loader:document.querySelector(".loader"),loader2:document.querySelector(".loader2"),loadBtn:document.querySelector(".load-btn")};function v(){r.loadBtn.classList.remove("hidden")}function g(){r.loadBtn.classList.add("hidden")}function w(){r.loader.classList.remove("hidden")}function E(){r.loader.classList.add("hidden")}function q(){r.loader2.classList.remove("hidden")}function p(){r.loader2.classList.add("hidden")}let c,i=1,l=1;const x=15;r.searchForm.addEventListener("submit",async a=>{if(a.preventDefault(),i=1,c=r.input.value.trim(),c===""){n.warning({title:"warning",message:"Search field can not be empty!",position:"topRight"});return}w(),r.picturesList.innerHTML="";try{const t=await m(c,i);if(l=Math.ceil(t.total/x),h(t.hits),E(),l===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",displayMode:"once"});return}y(),B()}catch{n.error({title:"Error"})}});r.loadBtn.addEventListener("click",async()=>{i++,g(),q();try{const a=await m(c,i);p(),h(a.hits)}catch{n.error({title:"Error"})}p(),O(),y()});function y(){i>=l?(g(),l!==0&&n.info({message:"We're sorry, but you've reached the end of search results."})):v()}function B(){r.searchForm.reset()}function O(){const t=r.picturesList.children[0].getBoundingClientRect().height;scrollBy({top:t,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
